apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fas5-ingress
spec:
  rules:
  - host: fas5.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fas5
            port:
              number: 80