apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fas5-prometheusrules
spec:
  groups:
  - name: fas5-rules
    rules:
    - alert: Fas5HighCpuUsage
      expr: cpu_usage > 0.7