apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fas5-prometheusrules
spec:
  groups:
  - name: fas5.rules
    rules:
    - alert: Fas5HighRequestLatency
      expr: increase(fas5_request_latency_bucket[1m]) > 0.5